language: java

jdk:
  - openjdk14

sudo: false

env:
  global:
    - CODECOV_TOKEN=335f119b-4bb6-4c62-b67c-cb7288e9e096

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонний сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      - cursedkun@gmail.com
    on_success: never # default: change
    on_failure: always # default: always